language: node_js
node_js: stable

install:
  - npm install

branches:
  only:
    - master

before_install:
  - echo "//npm.huanleguang.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm config set @gaoding:registry https://npm.huanleguang.com

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"

script:
  - npm run build

before_deploy:
  - export VERSION_TAG=`node -p "require('./package.json').version"`
  - git tag $VERSION_TAG
  - git add ./out
  - git push -f https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git `npm version patch -m "%s [ci skip]"` # 打 Tag，发布到 Github Release, 使用 [ci skip] 调过 CI， 防止死循环
  - git push -f --tags https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git HEAD:master #将新版本文件推送回 Github

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: $VERSION_TAG
  file:
    - "out/index.js"
  skip_cleanup: true
  draft: true
