language: node_js
node_js: stable

install:
  - npm install

branches:
  only:
    - master

before_install:
  - echo "//npm.huanleguang.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm config set @gaoding:registry https://npm.huanleguang.com

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"
  - export VERSION_TAG=`node -p "require('./package.json').version"`

script:
  - npm run build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: $VERSION_TAG
  skip_cleanup: true
  draft: true

after_deploy:
  - git add ./out
  - git commit -m "[skip travis] Release" # 防止死循环
  - git tag $VERSION_TAG
  - git push -f --tags https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git HEAD:master #将新版本文件推送回 Github