language: node_js
node_js: stable

before_install:
  - echo "//npm.huanleguang.com/:_authToken=\${NPM_TOKEN}" >> .npmrc
  - echo "//registry.npmjs.org/:_authToken=${PUBLISH_TOKEN}" >> .npmrc
  - npm config set @gaoding:registry https://npm.huanleguang.com
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"
  - export VERSION_TAG=`node -p "require('./package.json').version"`
  - export PKG_NAME=`node -p "require('./package.json').version"`

install:
  - npm install

branches:
  only:
    - master

script:
  # if pull request, todo 检查 PR 格式
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "check pr";
    fi

  # todo 运行测试
  - echo "Run tests"

  - npm run build

  # direct push to master
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      git add ./out &&
      git commit -m "[skip travis] Release" &&
      git tag $VERSION_TAG &&
      git push -f --tags https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git HEAD:master &&
      curl https://cdn.jsdelivr.net/gh/${TRAVIS_REPO_SLUG}@$VERSION_TAG/out/index.js > temp.js &&
      npm publish &&
      curl https://cdn.jsdelivr.net/npm/$PKG_NAME@$VERSION_TAG/out/index.js > temp.js;
    fi
