language: node_js
node_js: stable

install:
  - npm install

branches:
  only:
    - master

before_install:
  - echo "//npm.huanleguang.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm config set @gaoding:registry https://npm.huanleguang.com

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"

script:
  - npm run build


before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "out/index.js"
  skip_cleanup: true
  draft: true
