language: node_js
node_js: stable

install:
  - npm install

branches:
  only:
    - master

before_install:
  - npm config set @gaoding:registry https://npm.huanleguang.com
  - echo "registry=https://registry.npmjs.org/" > .npmrc
  - echo "home=https://www.npmjs.org" > .npmrc

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"

script:
  - npm run build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "out/index.js"
  skip_cleanup: true
  on:
    tags: false