language: node_js
node_js: stable

install:
  - npm install

branches:
  only:
    - master

before_script:
  - git config --global user.name "yudan"
  - git config --global user.email "yudan@gaoding.com"

script:
  - npm run build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "out/index.js"
  skip_cleanup: true
  on:
    tags: false